name: Deploy Backend to Cloud Run

on:
  push:
    branches:
      - main
    paths:
      - 'server/**'
      - '.github/workflows/deploy-backend.yml'
  workflow_dispatch:

env:
  PROJECT_ID: bitumenapp
  REGION: us-central1
  SERVICE: bitumenapp-api
  REPOSITORY: bitumenapp
  IMAGE_NAME: bitumenapp-backend

jobs:
  deploy:
    name: Build and Deploy API
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/324773145661/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: github-deployer@bitumenapp.iam.gserviceaccount.com

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Configure Artifact Registry auth
        run: |
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Build and push container image
        working-directory: server
        run: |
          IMAGE_URI="${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY}/${IMAGE_NAME}"
          echo "IMAGE_URI=${IMAGE_URI}" >> "$GITHUB_ENV"
          gcloud builds submit --tag "${IMAGE_URI}" .

      - name: Deploy to Cloud Run
        run: |
          if [ -z "${IMAGE_URI}" ]; then
            IMAGE_URI="${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY}/${IMAGE_NAME}"
          fi
          gcloud run deploy "${{ env.SERVICE }}" \
            --image "${IMAGE_URI}" \
            --region "${{ env.REGION }}" \
            --platform managed \
            --project "${{ env.PROJECT_ID }}" \
            --allow-unauthenticated \
            --port 8000
